###############################
#							  #
# RightClickCommand			  #
#							  #
# Developed by A_Brave_Panda  #
#							  #
###############################
#
commands:
    - "say Hi %player%"
    - "say Hello"